services:
  postgres:
    image: postgres:17
    container_name: cloudops-postgres

    environment:
      POSTGRES_USER: cloudops
      POSTGRES_PASSWORD: cloudops_password
      POSTGRES_DB: cloudops

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudops -d cloudops"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend

    container_name: cloudops-backend

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql+psycopg://cloudops:cloudops_password@postgres:5432/cloudops

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: